@baseUrl = http://localhost:3333

GET {{baseUrl}}/tasks

###

# @name createTask
POST {{baseUrl}}/tasks
content-type: application/json

{
  "title": "Lavar a louça",
  "description": "Precisa ser feito até às 18h"
}

###

@taskId = {{createTask.response.body.$.id}}

###

PUT  {{baseUrl}}/tasks/{{taskId}}
content-type: application/json

{
  "title": "Estudar programação",
  "description": "Estudar promises em node.js"
}

###

PATCH   {{baseUrl}}/tasks/{{taskId}}/completed
content-type: application/json

{
  "completed": true
}

