GET http://localhost:3333

###

POST http://localhost:3333
content-type: application/json

{
  "title": "Lavar a louça",
  "description": "Precisa ser feito até às 18h"
}

###

POST http://localhost:3333
content-type: application/json

{
  "title": "Estudar programação",
  "description": "Estudar promises em node.js"
}

